name: Deploy Docker Image

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: docker build . --file Dockerfile --tag danielecr/dconedo:${{ github.ref_name }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: danielecr
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push Docker image
      run: docker push danielecr/dconedo:${{ github.ref_name }}
